web/router.ex
defmodule Shlack.Router do
  use Shlack.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  scope "/", Shlack do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/", PageController, :index
    delete "/logout", AuthController, :logout
    get "/credentials", AuthController, :credentials
    get "/signup", SignupController, :new
  end

  scope "/auth", Shlack do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/:identity", AuthController, :login
    get "/:identity/callback", AuthController, :callback
    post "/:identity/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Shlack do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Shlack.LayoutView do
  use Shlack.Web, :view

  def show_flash(conn) do
    get_flash(conn) |> flash_msg
  end

  def flash_msg(%{"info" => msg}) do
    ~E"<div class='c-banner c-banner--success c-banner--unpinned'>
        <%= msg %>
        <i class='u-l-fr typcn typcn-delete' id='close-alert'></i>
       </div>"
  end

  def flash_msg(%{"error" => msg}) do
    ~E"<div class='c-banner c-banner--error u-mar-bottom-m c-banner--unpinned'>
        <%= msg %>
        <i class='u-l-fr typcn typcn-delete' id='close-alert'></i>
      </div>"
  end

  def flash_msg(_) do
    nil
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= if Guardian.Plug.current_token(@conn) do %>
      <meta name="guardian_token" content="<%= Guardian.Plug.current_token(@conn) %>" username="<%= @current_user.name %>">
    <% end %>

    <title>Shlack</title>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <nav class="shlack-nav">
      <div class="ul-wrap">
        <ul class="nav-ul">
          <li>Shlack</li>
          <%= render "login_bar.html", current_user: @current_user, conn: @conn %>
        </ul>
      </div>
    </nav>
    <main>
      <%= show_flash(@conn) %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/login_bar.html.eex
<%= if @current_user do %>
    <li><%= @current_user.name %></li>
    <li><%= link "Logout", to: auth_path(@conn, :logout), method: :delete %>
          </li>  
<% else %>
    <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
      <li>
        <%= link "Login", to: auth_path(@conn, :login, "identity") %>
      </li>
    <% end %>
<% end %>